version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: 'circleci/node:12.0-browsers'
    steps:
      - checkout
      - run:
          name: Show current branch
          command: 'echo ${CIRCLE_BRANCH}'
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: >-
            v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1
            }}
          paths:
            - dist
      - save_cache:
          key: >-
            v1-bin-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1
            }}
          paths:
            - bin
      - save_cache:
          key: >-
            v1-amplify-{{ .Environment.CIRCLE_BRANCH }}-{{
            .Environment.CIRCLE_SHA1 }}
          paths:
            - amplify
  deploy:
    working_directory: ~/project
    docker:
      - image: 'circleci/node:12.0-browsers'
    steps:
      - run:
          name: Show current branch
          command: 'echo ${CIRCLE_BRANCH}'
      - restore_cache:
          key: >-
            v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1
            }}
      - restore_cache:
          key: >-
            v1-bin-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1
            }}
      - restore_cache:
          key: >-
            v1-amplify-{{ .Environment.CIRCLE_BRANCH }}-{{
            .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Amplify CLI
          command: sudo npm install -g @aws-amplify/cli
      - run:
          name: Deploy
          command: |
            chmod +x bin/amplify-headless-init.sh
            ./bin/amplify-headless-init.sh
            amplify push --yes
            amplify publish --yes
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
